# Site settings
title: Joey Li

# Build settings
markdown: kramdown
permalink: pretty

# collections
collections:
  people:
    output: true
    permalink: /:collection/:name/
  places:
    output: true
    permalink: /:collection/:name/