# Site settings
title: Joey&nbsp;Li&nbsp;Photography

# Build settings
markdown: kramdown
permalink: pretty

# collections
collections:
  people:
    output: true
    permalink: /:collection/:name/
  places:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "picture"
  - scope:
      path: ""
      type: "places"
    values:
      layout: "picture"